# Generated by Django 4.2.11 on 2025-03-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Comment out or remove the CreateModel operation for Hanzi
        # migrations.CreateModel(...), 
        
        # Keep the Category model creation
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '汉字类别',
                'verbose_name_plural': '汉字类别',
            },
        ),
        migrations.CreateModel(
            name='Hanzi',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='编号')),
                ('character', models.CharField(max_length=1, unique=True, verbose_name='汉字')),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
                ('stroke_count', models.IntegerField(verbose_name='笔画数')),
                ('structure', models.CharField(choices=[('未知结构', '未知结构'), ('左右结构', '左右结构'), ('上下结构', '上下结构'), ('包围结构', '包围结构'), ('独体结构', '独体结构'), ('品字结构', '品字结构'), ('穿插结构', '穿插结构')], default='未知结构', max_length=20, verbose_name='结构类型')),
                ('stroke_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='笔顺')),
                ('pinyin', models.CharField(blank=True, max_length=50, null=True, verbose_name='拼音')),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, verbose_name='等级')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评语')),
                ('variant', models.CharField(choices=[('简体', '简体'), ('繁体', '繁体')], default='简体', max_length=10, verbose_name='简繁体')),
                ('standard_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='标准图片路径')),
                ('crt_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'hanzi',
            },
        ),
    ]
