# Generated by Django 4.2.11 on 2025-03-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi_app', '0001_initial'),
    ]

    operations = [
    ]
