# Generated by Django 4.2.11 on 2025-03-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi_app', '0002_auto_20250304_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanzi',
            options={'managed': False},
        ),
    ]
