# Generated by Django 4.2.11 on 2025-03-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi_app', '0003_alter_hanzi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanzi',
            options={'managed': True, 'verbose_name': '汉字数据', 'verbose_name_plural': '汉字数据'},
        ),
    ]
