# Generated by Django 4.2.11 on 2025-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanzi_app', '0004_alter_hanzi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hanzi',
            name='character',
            field=models.CharField(max_length=1, verbose_name='汉字'),
        ),
    ]
